### ISSUE TITLE
YAML Configuration has erratic behaviour

### ISSUE THREAD

**Issue by adrienbeaussier** [meshtastic/python#384]
Hello,

I am trying to configure my T-Beam (M8N & SX1262) devices using meshtastic CLI and the newly updated configuration feature. (`--config`)

When doing so, it sometimes runs without an error and reboots but config is still the same when running again `--info`. This happened with [this file](https://pastebin.com/Zw5TTzA7).
I first posted on Discord under #python and following garth advices I tried again with a file that didn't have maxint values in the "position" section, however behaviour was the same: nothing happens on first try, I get a connection error and time-out on the second one. (see [error.log](https://github.com/meshtastic/Meshtastic-python/files/9794270/error.log), obtained using [this yml file](https://pastebin.com/2MhaLkD6), and same happened using [this one](https://pastebin.com/DRxujN1D))

Here are my `--support` and `--info` outputs. Please note that these issues happened on different devices, with different cables and on different ports, and that I never had such connection issue with one of my devices when using regular CLI commands.
[support-info.log](https://github.com/meshtastic/Meshtastic-python/files/9794269/support-info.log)

Thank you

**Comment by ctodd** [comment]
I'll add several issues here which are related to this, specifically trying to re-import config from the export :

1. owner_short is getting saved as three characters regardless of what the last character(s) is, or position in the yaml file. I'm thinking this may be a firmware bug, not an issue with the Python command, and it doesn't seem to happen on all of my identical devices.
2. The Range Test module config is exported in camelCase and won't import : "Error: No valid config with name rangeTest". Changing to snake_case in the yaml file seems to fix this, but "enabled: false" has no effect. Seems like this may be a firmware bug.
3. Telemetry module displays Environment on screen if "environmentScreenEnabled: true" when the module itself is disabled.
4. Setting any parameter to false causes it to be dropped from the --export-config and --info. This may be by design to conserve storage though.
5. User defined channel config is not exported (would be nice for bulk provisioning, but can be scripted)
6. Setting lora hopLimit is ignored and gets set to the default of 3.
7. Nothing in the store_forward module configuration gets saved to the device, doesn't work with --set either.

I am using 1.3.45 firmware, and meshtastic-python 1.3.42

**Comment by thebentern** [comment]
3) This by design. Enabling the module turns on the sending of telemetry. Enabling the screen setting just lets you observe remote telemetry.

4) Correct. 0 in protobufs is essentially a null

Seems like some of the others are bugs either in python or device side.
