### ISSUE TITLE
PEP 224: Point of information

### ISSUE THREAD

**Issue by holdenweb** [meshtastic/python#533]
I notice that at https://github.com/meshtastic/python/blob/218e9b969ac3a717da7d76f4d153db108d6b1345/meshtastic/__init__.py#L98 the code assumes PEP 224 is a thing. Unfortunately, if you read the PEP you will find it was rejected, so the docstrings (for which I applaud the author) might just as well be comments. This may reduce the size of compiled files slightly, but otherwise should make absolutely no difference.

**Comment by ianmcorvidae** [comment]
PEP224 is relevant due to our current use of `pdoc`, which uses them: https://pdoc3.github.io/pdoc/doc/pdoc/#docstrings-for-variables

While `pdoc` does support `#:` type comments instead, I'm not sure there's good reason to swap them over. It's possible `pdoc` won't serve our needs (still need to get the documentation back online in some form), at which point they could possibly be changed as well.
