### ISSUE TITLE
Meshtastic Python 2.3.14 fails on devices with 2.3.15 firmware

### ISSUE THREAD

**Issue by cha0swir3** [meshtastic/python#642]
Seeing the following issue after upgrading Heltec V3 radio to 2.3.15 firmware. Python 2.3.14 can no longer interact with it via serial.

![MT_2 3 14_error](https://github.com/user-attachments/assets/19552e03-3bde-49a9-a103-c81329fe026a)

**Comment by ianmcorvidae** [comment]
This is now a quite old version of the CLI; I think that this should be closed for now. Timing out on connection completion isn't particularly abnormal, but if you can reproduce the DecodeError with a more recent version and include `--debug`, then potentially there is a fix there. The error handling around that code has been updated since this bug report already, though.
