### ISSUE TITLE
Changing channel preset over admin channel fails on congested networks

### ISSUE THREAD

**Issue by jonootto** [meshtastic/python#662]
Attempting to set the channel preset over admin channel goes into a loop of requesting channel information which almost inevitably times out in a congested mesh, is this necessary? Could an option be added to skip fetching current config?

> meshtastic --host 192.168.1.10 --dest '!xxx' --ch-shortfast
Connected to radio
Requesting channel 0 info from remote node (this could take a while)
Requesting channel 1 info from remote node (this could take a while)
Requesting channel 2 info from remote node (this could take a while)

**Comment by jonootto** [comment]
This was after about 20 attempts where the majority hung on channel 0, none successfully got the point of sending the new config

**Comment by ianmcorvidae** [comment]
I think those `--ch-x` commands should be able to work over admin too, but I don't know why they're requesting every channel. I'll need to check if they're doing something other than just setting the preset but hopefully we can disable the channel fetching at least. Until then, using `--set` is a good idea, since it'll only need to fetch the config for that.

**Comment by jonootto** [comment]
Thanks folks, confirm the --set option has worked fine, do you want to keep this open to look into the --ch commands?

**Comment by ianmcorvidae** [comment]
Yeah, I'd like to check on those still. If they're really just setting the preset, maybe we can streamline some stuff. If they're doing more, we should document the differences, so either way let's leave this open, and thanks for the report!
